name: deploy myblog

on:
    push:  # 当main分支被push，以及paths里面定义的被改变时，触发xxx命令
        branches: 
            - 'main' #push操作时，对应的分支
        paths: 
            - '.github/workflows/*' #  什么文件或者文件夹里的文件变动时，触发
            - 'src/*'
            - 'package.json'
            - 'bin/*'

jobs: 
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - uses: actions/checkout@v4 #使用哪一个已经好了的action，除了这个action之外，还有其他功能的action

            - name: set id_rsa # 设置id_rsa
              uses: ssh-action@v2 # 使用ssh-action
              with:
                key: ${{ secrets.ALIYUN_ESC_SECRET }} # 这是在github的settings/secrets and variables/actions中设置的
                #known_hosts: ${{ secrets.KNOWN_HOSTS }} 

            - name: deploy # 部署
              run: |
                cd /project/blogs/server
                git pull
                npm install
                npm run build
                pm2 restart myblog

